groups: 
  - 281460675321367 # Track posts of this group. This is the id for the group Programmatori a Catania
  - 110929722279430 # Informatici a Palermo
pages: 
  - 116505148430596  # YoutHub
  - 371576386279313  # EESTEC Catania
  - 1486797638277248 # CoderDojo Etneo
  - 887171771350676  # ATFactory
  - 1457341927813814 # Hackspacee Catania
  - 859949567453237  # MPS Catania
  - 1380906508817529 # Startup Messina
  - 146290095529300  # Consorzio Arca
  - 444735402236013  # GDG Catania
  - 875340082514949  # Vulcanic
  - 150423961659353  # Impact Hub Siracusa
  - 189873531201389  # Fablab CT
  - 173047699475869  # Startupweekendcatania